id: PF3E1AF9E
initial_creation_type: input
source_metadata:
  title: Pari Lobzang Rabsal
  language: bo
  description: 'Texts by and about Pari Lobzang Rabsal (dpa'' ris blo bzang rab gsal,
    1840–c.1912), the Gelugpa scholar famous for his opposition to Jamgön Mipham''s
    interpretation of Madhyamaka philosophy:'
  volume:
    7e96dbd8ef6f4abf9dacb5e3b2ff0485:
      title: An Appeal for the Prosperity of Teaching and Studying the Five Major
        Scriptures
      parent: Summoning Prosperity
created_at: '2022-03-01T01:10:37.817708'
last_modified_at: '2022-03-01T01:10:37.817711'
